# Generated by Django 6.0.1 on 2026-01-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bid_image_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
